name: tomATOCD
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - snakemake-minimal>=8.0
  - pandas>=2.1
  - pyyaml
  - numpy
  - scipy
  - r-base=4.3
  - r-essentials
  - r-tidyverse
  - r-voronoitreemap
  - r-htmlwidgets
  - r-webshot
  - r-webshot2
  - r-yaml
  - r-knitr
  - r-rmarkdown
  - r-argparse
  - r-testthat
  - pip:
      - pyarrow
